"""m1 categories

Revision ID: 518529eacb3e
Revises: a86777119302
Create Date: 2026-07-09 10:19:01.820763
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '518529eacb3e'
down_revision: Union[str, None] = 'a86777119302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pg_trgm:后续 SKU search_text 的 GIN 索引依赖此扩展,提前建;幂等。
    # (autogenerate 不会发出扩展 DDL,手工加;downgrade 不 DROP 共享扩展)
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('parent_code', sa.String(length=50), nullable=True),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_leaf', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_code'], ['categories.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    # 范围兜底(autogenerate 不比对 CHECK,手工内联)
    sa.CheckConstraint('level >= 1', name='ck_categories_level'),
    sa.CheckConstraint('sort_order >= 0', name='ck_categories_sort_nn')
    )
    op.create_index(op.f('ix_categories_parent_code'), 'categories', ['parent_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_parent_code'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
