"""m1 spu sku

Revision ID: 14e188130cf8
Revises: 103eb408942b
Create Date: 2026-07-09 22:36:38.825259
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14e188130cf8'
down_revision: Union[str, None] = '103eb408942b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_code'], ['categories.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spus_category_code'), 'spus', ['category_code'], unique=False)
    op.create_table('skus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spu_id', sa.Integer(), nullable=False),
    sa.Column('sku_code', sa.String(length=30), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('reference_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('spec_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['spu_id'], ['spus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_skus_search_text_trgm', 'skus', ['search_text'], unique=False, postgresql_using='gin', postgresql_ops={'search_text': 'gin_trgm_ops'})
    op.create_index(op.f('ix_skus_sku_code'), 'skus', ['sku_code'], unique=True)
    op.create_index(op.f('ix_skus_spu_id'), 'skus', ['spu_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skus_spu_id'), table_name='skus')
    op.drop_index(op.f('ix_skus_sku_code'), table_name='skus')
    op.drop_index('ix_skus_search_text_trgm', table_name='skus', postgresql_using='gin', postgresql_ops={'search_text': 'gin_trgm_ops'})
    op.drop_table('skus')
    op.drop_index(op.f('ix_spus_category_code'), table_name='spus')
    op.drop_table('spus')
    # ### end Alembic commands ###
