"""m1 quotations

Revision ID: 4aee6cdbe0b6
Revises: 14e188130cf8
Create Date: 2026-07-09 22:48:40.578656
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aee6cdbe0b6'
down_revision: Union[str, None] = '14e188130cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('no', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_orders_customer_id'), 'quotation_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_quotation_orders_no'), 'quotation_orders', ['no'], unique=True)
    op.create_table('quotation_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quotation_order_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('name_snapshot', sa.Text(), nullable=False),
    sa.Column('spec_text_snapshot', sa.Text(), nullable=False),
    sa.Column('unit_snapshot', sa.String(length=20), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quotation_order_id'], ['quotation_orders.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    # 金额/数量/排序 DB 兜底(应用层 Pydantic 已给 400,这里防直连/回归)
    sa.CheckConstraint('qty > 0', name='ck_qlines_qty_pos'),
    sa.CheckConstraint('unit_price >= 0', name='ck_qlines_unit_price_nn'),
    sa.CheckConstraint('line_total >= 0', name='ck_qlines_line_total_nn'),
    sa.CheckConstraint('sort_order >= 0', name='ck_qlines_sort_nn')
    )
    op.create_index(op.f('ix_quotation_lines_quotation_order_id'), 'quotation_lines', ['quotation_order_id'], unique=False)
    op.create_index(op.f('ix_quotation_lines_sku_id'), 'quotation_lines', ['sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotation_lines_sku_id'), table_name='quotation_lines')
    op.drop_index(op.f('ix_quotation_lines_quotation_order_id'), table_name='quotation_lines')
    op.drop_table('quotation_lines')
    op.drop_index(op.f('ix_quotation_orders_no'), table_name='quotation_orders')
    op.drop_index(op.f('ix_quotation_orders_customer_id'), table_name='quotation_orders')
    op.drop_table('quotation_orders')
    # ### end Alembic commands ###
